name: Wisecow CI/CD

on:
  push:
    branches:
      - main
  pull_request:

env:
  IMAGE_NAME: lovepreetsingh3028/wisecow
  K8S_DEPLOYMENT: wisecow-deployment
  K8S_NAMESPACE: default

jobs:
  build-and-push:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t $IMAGE_NAME:latest .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:latest

  deploy-to-k8s:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.34.0'

      - name: Configure Kubeconfig
        run: |
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Update Kubernetes Deployment
        run: |
          kubectl set image deployment/$K8S_DEPLOYMENT \
          wisecow-container=$IMAGE_NAME:latest \
          -n $K8S_NAMESPACE

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/$K8S_DEPLOYMENT -n $K8S_NAMESPACE
